### PR TITLE
Add disclaimer to API docs

### PR DESCRIPTION
**Pull request by ezequielc**
As discussed a couple os weeks ago. Thanks
@Rise-Vision/apps Please review

Staged at: https://help-stage.risevision.com/chore-api-disclaimer/_site/developer

### CODE REVIEW

**Comment by fjvallarino** [comment]
:+1:

**Comment by alex-deaconu** [comment]
@ezequielc looks good 👍 .

Just one suggestion, do you think it's possible to make that warning "sticky" so it shows on every page? 

Thanks.

**Comment by ezequielc** [comment]
@alex-deaconu I think it would be too prominent. I think it is fine to have it only in the initial page. Thoughts? Thanks

**Comment by alex-deaconu** [comment]
@ezequielc I'm good either way, I guess it depends on how much attention we want to draw to this warning. Thanks.

**Comment by ezequielc** [comment]
@alex-deaconu I think we can go with it for now. We can always add it to other pages later if needed. Thanks

**Pull request merged**
