### PR TITLE
Updated ch version

### PR DESCRIPTION
**Pull request by rodrigopavezi**
@alex-deaconu  @btfrise please review. https://help-stage.risevision.com/chore-update-ch-version/_site/

This is a fix for the https://github.com/Rise-Vision/common-header/issues/536 issue.

cheers

### CODE REVIEW

**Comment by rodrigopavezi** [comment]
@olegrise sorry, I should have asked you to review. cheers

**Comment by olegrise** [comment]
@rodrigopavezi why v1.2.4, but not v1.3.2 ?

**Comment by rodrigopavezi** [comment]
@olegrise I missed that. I thought 1.3.2a was not stable yet. I will change to it. cheers

**Comment by rodrigopavezi** [comment]
@olegrise updated. cheers

**Comment by olegrise** [comment]
@rodrigopavezi You are right `v1.3.2a` is not stable yet, it's not merged to master, and I was not suggesting it. I said version `v1.3.2` :)
Anyway, I just created new tag  `v1.3.3` for the most recent commit merged to master. Please use that. Sorry for confusion.

**Comment by rodrigopavezi** [comment]
@olegrise no worries, updated it to v1.3.3. cheers

**Comment by olegrise** [comment]
:+1:

**Pull request merged**
