### PR TITLE
Doc banner tracking

### PR DESCRIPTION
**Pull request by RV-Adrian**

### CODE REVIEW

**Comment by brianloosbrock** [comment]
@rodrigopavezi @RV-Adrian Can you guys have a chat on this to determine what needs to be resolved so we can deploy the changes to track the banner clicks on https://help.risevision.com/user/create-a-display. Thanks

**Comment by rodrigopavezi** [comment]
@brianloosbrock @RV-Adrian I have already fixed the issue but this PR has to be rebased so it can be merged. cheers

**Comment by brianloosbrock** [comment]
@RV-Adrian Can you rebase it when you get a chance so we can merge and close this off. Thanks!

**Comment by brianloosbrock** [comment]
@RV-Adrian Can you rebase this so we can deploy and get this closed off. Thanks

**Comment by RV-Adrian** [comment]
@brianloosbrock @rodrigopavezi 
Rebased and staged here, thanks
https://help-stage.risevision.com/doc-banner-tracking/_site/user/create-a-display

**Comment by brianloosbrock** [comment]
@RV-Adrian I noticed the segment isn't being logged now, it is 'Promotional Banner Clicked'

It was before if I recall correctly. 

Thanks

**Comment by RV-Adrian** [comment]
@brianloosbrock Good catch, I'll see what's up. There is also some pending changes to this stemming from https://trello.com/c/9NLBDzuU/1007-ux-simplify-player-download-options-2
which I am hoping to wrap up today. I will adjust the tracking at the same time and close the task.

**Comment by ByronDarlison** [comment]
@RV-Adrian @brianloosbrock is this on a board somewhere and are their points coming out for it? Thanks

**Comment by brianloosbrock** [comment]
@ByronDarlison @RV-Adrian Sorry, missed this question. Yes, there is a card here https://trello.com/c/tpf54tYE/903-media-player-banner-tracking-in-documentation-2 on the Store board. The segment event needs to be fixed and then we can close it off. Its not blocking anything, I just want to get it closed off. Thanks.

**Comment by RV-Adrian** [comment]
@rodrigopavezi 
I am getting a `Build Warning: Layout ... does not exist` error when I build. 
Can you see what might be the problem locally when you have a moment? Thanks!

**Comment by rodrigopavezi** [comment]
@RV-Adrian As the new Documentation does not have CH anymore I had to remove the reference to the userState and CH on the files. That fixed the build. Please review. cheers

**Comment by RV-Adrian** [comment]
Thanks @rodrigopavezi! I will try it out.

@brianloosbrock Looking to wrap this up by end of day, sorry for the delay.

**Comment by RV-Adrian** [comment]
@rodrigopavezi 
I pulled the changes but now see ' AssertionError: expected 'http://10.0.4.1:8099/developer' to equal 'Rise Vision Developer Documentation | Rise Vision API'

Any thoughts? Thanks!

**Comment by brianloosbrock** [comment]
@RV-Adrian Thanks.

**Comment by RV-Adrian** [comment]
@brianloosbrock 
It came up at Standup that the removal of CH would affect the tracking we had set up earlier (in that a new method would be needed).
That, along with the CH removal causing some build issues, I'd say the scope of this card has increased enough to cause some context-switching for myself.  Could the Banner tracking be a Store task from here?

FYI @rodrigopavezi @ByronDarlison

**Pull request closed without merging**
