### PR TITLE
Doc/chromeos managed

### PR DESCRIPTION
**Pull request by btfrise**
@alanclayton @mfisher11 @justinsmith1 Please review using the standards here https://docs.google.com/document/d/1pvbypKELzXrQcQ24JG-o4kET5ZNqtkGHbgbrfS9atDo/edit

This is staged at https://help-stage.risevision.com/doc-chromeos-managed/_site/user/advanced/display/configure-kiosk-mode

### CODE REVIEW

**Comment by mfisher11** [comment]
@btfrise Take a look at item numbers (not line numbers) 7 and 8.  Not sure about item number 5 in Enroll your chromebox.  Should the choices be italicized and not bold?  Nothing else jumps out at me.

**Comment by btfrise** [comment]
@mfisher11 good catch. Thanks,

**Comment by btfrise** [comment]
@alanclayton any input?

**Comment by alanclayton** [comment]
@btfrise the steps you show to enroll a device are not the same as what you proposed in your doc. Thanks

**Comment by btfrise** [comment]
@alanclayton Good catch, I missed that nested bullet. These now match.

**Pull request merged**
