### PR TITLE
Remove Rise Storage Web Component section

### PR DESCRIPTION
**Pull request by donnapep**

### CODE REVIEW

**Comment by donnapep** [comment]
@stulees Please review. Thx.

**Comment by stulees** [comment]
@donnapep Do you know why the `Gemfile.lock` change is included in this?

**Comment by donnapep** [comment]
@stulees That's what happened when I built the repo. @rodrigopavezi Is that deletion a problem? Thx.

**Comment by donnapep** [comment]
@stulees I just reverted the change to that file. Should be good now.

**Comment by stulees** [comment]
@donnapep The file is still in included but its keeping the line in. :+1: anyway

**Pull request merged**
