### PR TITLE
Chore/seo

### PR DESCRIPTION
**Pull request by rodrigopavezi**
Changed links from relative to absolute.

@alex-deaconu I have added some metadata for Googles SEO and I have also changed the links to absolute links so the crawlers can navigate better through the site. This was need as prerender was caching unknown urls made up by the crawlers as the links were not absolute.

Could you please review? cheers.

### CODE REVIEW

**Comment by alex-deaconu** [comment]
@rodrigopavezi looks good. 

Two questions:
Instead of having `{{site.url}}{{site.basehref}}{{site.hashTag}}` in front of every link (all 3 components), couldn't you just create a variable like `{{site.baseurl}}` to use for this? 
Also, could you use Angular one time binding to bind for the url values (`{{:: site.baseurl}}`) since these are pretty much final/constant links. 

Thanks.

**Comment by rodrigopavezi** [comment]
@alex-deaconu Agreed. I have changed it to use only one variable {{site.absoluteurl}}. {{site.baseurl}} is already used internally by jekyll.
Regarding the second question, I don't think it applies here as the {{}} is jekyll binding. As angular and jekyll have the same binding syntax. To make them coexist we have to do something like the following when doing angular binding.

 {% if page.type == 'developer' %}
            <h1>{% raw %}  {{'DEVELOPER_DOCS' | translate}} {% endraw %}</h1>
        {% elsif page.type == 'user' %}
            <h1>{% raw %}{{'USER_DOCS' | translate}}{% endraw %}</h1>
        {% endif %}

We need to put angular binding into {%raw%}{%endraw%}

Cheers

**Comment by alex-deaconu** [comment]
@rodrigopavezi thanks for fixing. :+1:

**Comment by rodrigopavezi** [comment]
@alex-deaconu thanks. I will squash it now.

**Pull request merged**
