### PR TITLE
User roles update w/storage changes.

### PR DESCRIPTION
**Pull request by btfrise**
@alanclayton @mfisher11  please review

### CODE REVIEW

**Comment by alanclayton** [comment]
@btfrise I don't see the updates on the stage site. Do you?

**Comment by btfrise** [comment]
@alanclayton I had to delete the existing doc. My table it all messed up in staging, I'm going to go back into haroo and take another look.

**Comment by btfrise** [comment]
@alanclayton @mfisher11 updated with fixed table. Please review.

**Comment by alanclayton** [comment]
@btfrise looks good

**Pull request merged**
