### PR TITLE
rename configure kiosk mode page due to broken link

### PR DESCRIPTION
**Pull request by mfisher11**
@btfrise Please review. I just removed the "-rev1" and left the date unchanged.  I don't know if that will be sufficient.

### CODE REVIEW

**Comment by mfisher11** [comment]
@alanclayton (copied from previous comment)  Please review. I just removed the "-rev1" and left the date unchanged. I don't know if that will be sufficient.

**Comment by btfrise** [comment]
@mfisher11 :+1: This looks good, thanks.

**Comment by alanclayton** [comment]
@mfisher11 Where is the Stage URL to review?

**Comment by mfisher11** [comment]
@alanclayton https://help-stage.risevision.com/doc-file-rename-fixes/_site/

**Comment by alanclayton** [comment]
@mfisher11 Looks good. Go ahead and merge.

**Pull request merged**
