### PR TITLE
Specify supported ubuntu ver

### PR DESCRIPTION
**Pull request by alanclayton**
@lapinnoir Made this change per the card https://goo.gl/A6yPWd for ya. Let me know if the change made  works. Thanks

### CODE REVIEW

**Comment by lapinnoir** [comment]
@alanclayton :+1:

**Comment by RV-Adrian** [comment]
@alanclayton @lapinnoir 
Displays App specifies 'LTS' while this Documentation update does not.
I appreciate the velocity, but this is how small details get fragmented.

I should not have included this as part of another card. My mistake. Lesson learned. :)

**Comment by alanclayton** [comment]
@RV-Adrian Good catch. See pr here https://github.com/Rise-Vision/risevision-documentation/pull/29

@lapinnoir FYI

**Comment by lapinnoir** [comment]
@RV-Adrian Thanks!

**Pull request merged**
