### PR TITLE
Fixing broken link in "Building a Multi-Page Presentation"

### PR DESCRIPTION
**Pull request by stulees**

### CODE REVIEW

**Comment by stulees** [comment]
@rodrigopavezi This PR is just a fix for a broken link, but the build failed. Looks to be a problem that I can't decipher, can you have a look? Thanks

**Comment by stulees** [comment]
@rodrigopavezi FYI, when I run tests locally, everything passes.

**Comment by stulees** [comment]
@rodrigopavezi Rebuilt and now it all passed ... please review, thanks.

**Comment by rodrigopavezi** [comment]
@stulees LG :+1: cheers

**Pull request merged**
