### PR TITLE
Adding developer hub code to help docs

### PR DESCRIPTION
**Pull request by alex-deaconu**
Deploy to developer & developer-stage sites

Update all URLs from /developer to /documentation

### CODE REVIEW

**Comment by alex-deaconu** [comment]
This PR is pretty much ready to go. Few extra steps I think would be helpful:

- remove `/user` routes (those are still accessible through direct URLs)
- merge & minify all files in the build

Staged at https://developer-stage.risevision.com/

@ezequielc @fjvallarino please review. Thanks!

**Comment by ezequielc** [comment]
@alex-deaconu The menu is falling to the next row in my screen, it seems it is too long.
screen shot 2017-05-23 at 9 16 37 pm
I think we can remove User Documentation and Training, as they are under the Need Help dropdown. Thoughts? Thanks

**Comment by alex-deaconu** [comment]
@ezequielc good catch. Updated as per your suggestion, and added a small improvement. Thanks!

**Comment by alex-deaconu** [comment]
@ezequielc @fjvallarino added minify CSS/JS tasks, fixed issues with i18n and did some cleanup all around. I think this PR is ready to go, wondering if you can do a final review of this and the other 2 PRs I have open for this:

https://github.com/Rise-Vision/docker-webserver/pull/87
https://github.com/Rise-Vision/common-i18n/pull/224

Thanks!

**Comment by fjvallarino** [comment]
@alex-deaconu looks good to me, although I may not be aware of all the expected changes.

:+1:

**Comment by ezequielc** [comment]
@alex-deaconu I played a bit with the documentation and links and it looks good. Thanks

**Comment by alex-deaconu** [comment]
Thanks for the review guys!

**Pull request merged**
