### PR TITLE
Matthew updates

### PR DESCRIPTION
**Pull request by mfisher11**
@alanclayton Ready for review...

### CODE REVIEW

**Comment by mfisher11** [comment]
@alanclayton or @btfrise   Look good?

**Comment by alanclayton** [comment]
@mfisher11 I don't think we need the page 2014-12-12-storage-settings.md

**Comment by mfisher11** [comment]
@rodrigopavezi Everything seems to have checked out with circleci, but it doesn't look like it got merged into staging.  Can you see anything?  Thanks.

**Comment by rodrigopavezi** [comment]
@mfisher11 let me have a look.

**Comment by rodrigopavezi** [comment]
@mfisher11 I know what happened. you must prefix your branch name. Circleci build is looking for some prefixes such as feature, fix, chore, doc and build: https://github.com/Rise-Vision/risevision-documentation/blob/master/circle.yml#L13 

So, naming it doc/matthew-updates will make your changes to be merged into stage. Would you like me to do that?

cheers

**Comment by mfisher11** [comment]
@rodrigopavezi I see.  Yes, please, and thank you very much.  I won't make the same mistake again.

**Comment by rodrigopavezi** [comment]
@alanclayton @mfisher11 please continue on the other PR https://github.com/Rise-Vision/risevision-documentation/pull/167. This PR will be closed.

**Pull request closed without merging**
